dist: xenial
language: python
python:
- '3.8'
- 3.8-dev
install:
- pip install -e .[dev]
script:
- tox
deploy:
  provider: pypi
  skip_existing: true
  user: __token__
  password:
    secure: wqrdToofADUziFfNdFcihp0Neo5aj8gcJrb3TEEO/Omjzjl2JHm8Epm2XuFwOoesWXBf6gWlMnuL7EBEALVKD4I6hXfFYuzVxIQBPwgK2GF+qbkamFp56Z9JYuNHqBc5suMYF65hRvs/pLQFstYOMv48Cw46IPdg6uq1qmAbQvvWKogLh5IQPS701tlXqbjfWrIBTuhkpaREWPT+2ITs2f3HeHQ0n0AC7n1ZpxSFm8xFnboRLHAsjf6tscrbyqZlVqEcEB91riWgtz9TNXc0NLbxSyt1oIH1ZVKLbvFro3KcmimTGVAxPsaWIg72lUck34GIdZfUk+1k4oPywLlks3MyKaQPx4FqCbJHqDrNnQyIjidQ7PG5coAwRSHiLOxGo7BcpxAbd4eiTrrRA9Rkt7DwnuRmn8w6JmEYmNXGBXdKIL+7ZT7P0n2BcuGdEstQOvAybqB40/UDnY9WBFtPQXuYQNayVlE9sn0MDKeePv4fkHKSpRdoKu4pN/T3+e6RuJCs/e1LuEeHBe2h1uiCMr5+T9To38PUrHDGCWD+8+j1Xsqw0ftmAoN4YO1++DNj+UEVlY7ej82CK5kSbFaYD5P85w+QZVXBZBkTeZuVNYyaFIUxkWPYF2C4OWmpSYRNSz9rfDmOrlIWieYQOWstMVK8iYGnUExcahOATXclgp4=
  on:
    branch: master
