dist: xenial
language: python
python:
- '3.8'
- 3.8-dev
install:
- pip install -e .[dev]
script:
- pylint obm tests -d C
- pytest -vrs
deploy:
  provider: pypi
  skip_existing: true
  user: __token__
  password:
    secure: qpwl/sHvv5j1uV7TrtRcEPp7fYIhOCAOOODE4haJJ9Oih/um8Ct5bLirjYWrVxO2gqBBzum3OnDHflHtI/uPrD/jHcHG0AZeJj+mvduu5uHkgYDVMu35JyBR1MzFYKVy0IlnFHg9i2LzdqeFPlUZri5O845CHXKbkofIaUPya1bkodT+yM+NVKB8XPfvb2d8h0VzrlReVU6myiM8/a5oIwVb4k0Pi5llzmesi2HZ7+Ad9iloNr8v7az2ZSQ9jwVwF9SP5CZfqlgBfLMkxMlKj5EcnqnFgxO5MmmAbIWSSCDpqKlEyUVvlHXNd1Sx++SQAOEc97Oj3tMBPCJjnEpHnwWihwHuxr1q6b70Tv2F+pzPm4fRtFeXq4nrmFjGlYthtnNn7cR0GkIEMxa2sLLN/k050pqmR526+UbYik9uAa1Lcu5/jKq04kwq789XFBa9392dROLbJamaKrkhpfuy9SzIsLTJbw4ASkRWwz5neUrSlzqhnH3lX9+FRyyHCOJj58KSZI3NRqG8sMmzIeaIX+cN7p7VB/BATjY2u1e0IRueP+3wSKDwhPPLQLfAZoKqCbe5SexCgQKPkYXFjmu8rqU88pU341XbFncFFjl8bgZp+Pd0uSlryli8A12f9K5glhPGuwP+8/m64t0+eEi+RMXqTMxeIKL+DkJ2ylcAI1I=
  on:
    branch: master
